### ISSUE TITLE
SignUp で未入力状態で「Sign up」ボタンが活性状態である

### ISSUE THREAD

**Issue by Mitsuru53** [s-hayashi1104/Automatic-creation-of-minutes#17]
非活性状態の方が望ましい
![2019-03-01 19 17 38](https://user-images.githubusercontent.com/23156390/53631930-0712ba80-3c57-11e9-87b3-f7538f872eeb.png)

**Comment by s-hayashi1104** [comment]
Pull request#21にて修正しました
