### ISSUE TITLE
nameキーにemailを登録している

### ISSUE THREAD

**Issue by Mitsuru53** [s-hayashi1104/Automatic-creation-of-minutes#18]
nameキーならname属性を登録すべき
emailはauthで取れるはずなので、特に理由がなければdbに保存する必要はないのでは
必要な場合でもemailキーに設定しましょう
https://github.com/s-hayashi1104/Automatic-creation-of-minutes/blob/d8b5c2d4ed709c5aef8e2b8fcd3ce41648a06765/server/setup.js#L12

**Comment by s-hayashi1104** [comment]
Pull request#21にて修正しました
