### ISSUE TITLE
生パスワードのまま

### ISSUE THREAD

**Issue by Mitsuru53** [s-hayashi1104/Automatic-creation-of-minutes#19]
生パスワードはNG
万が一パスワードが漏洩した時を考えてみてください
一発アウトです

というかpasswordもauthで取得できるのでdbに保存する必要がないのでは...?
https://github.com/s-hayashi1104/Automatic-creation-of-minutes/blob/d8b5c2d4ed709c5aef8e2b8fcd3ce41648a06765/server/setup.js#L17

**Comment by s-hayashi1104** [comment]
Pull request#21にて修正しました
